jwt:
  expiration:
    access: 7200000  # 1000 * 60 * 120 = 2 hour
    refresh: 12096000000 # 1000 * 60 * 120 = 2 weeks

  secret: aGVsbG9JJ21zdHVkeWluZ25vd3NwcmluZ1NlY3VyaXR5ISFJdCdzVmVyeUhhcmRCdXRJQ2FuRE9pVDs7ZnVja2luZ3NwcmluZ3NlY3VyaXR5YnV0SUxpa2VJdA