spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 6TUrM1BdYJexwaWehYak
            client-secret: 39RzoCIO0l
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response